// Combat resolution math (GDD §4). Pure functions of numbers — no state, no RNG,
// no wall-clock. The sim resolver (Part 3) and the client tooltips both call these,
// and the Phase-6 server runs them as the authority. Every formula here is a direct
// transcription of GDD §4; keep them in sync (and write tuning back to the GDD).

import { CRIT_MULTIPLIER } from '../data/stats.js';

/** AP contribution to a weapon swing: AP/14 × weaponSpeed (GDD §4 derived). */
export const WEAPON_AP_DIVISOR = 14;

/**
 * Damage of one weapon swing: `baseRoll + AP/14 × weaponSpeed`. `baseRoll` is the
 * weapon's rolled base damage; slower weapons hit harder per swing.
 */
export function weaponDamage(baseRoll: number, weaponSpeed: number, attackPower: number): number {
  return baseRoll + (attackPower / WEAPON_AP_DIVISOR) * weaponSpeed;
}

/**
 * Damage of a skill: `coefficient × source × classModifier`, where `source` is the
 * attacker's weaponDamage (physical) or spell power (magic). `classModifier`
 * folds in Path/talent multipliers (default 1).
 */
export function skillDamage(coefficient: number, source: number, classModifier = 1): number {
  return coefficient * source * classModifier;
}

// --- Armor mitigation (physical only) ---
export const ARMOR_LEVEL_COEFF = 85;
export const ARMOR_CONST = 400;
export const ARMOR_MITIGATION_CAP = 0.75;

/** Fraction of physical damage removed by `armor` vs an attacker of `attackerLevel`. */
export function armorMitigation(armor: number, attackerLevel: number): number {
  if (armor <= 0) return 0;
  const raw = armor / (armor + ARMOR_LEVEL_COEFF * attackerLevel + ARMOR_CONST);
  return Math.min(ARMOR_MITIGATION_CAP, raw);
}

/** Apply armor to a raw physical hit. */
export function mitigatePhysical(raw: number, armor: number, attackerLevel: number): number {
  return raw * (1 - armorMitigation(armor, attackerLevel));
}

// --- Level difference (GDD §4) ---
export const LEVEL_DELTA_DMG_PER_LEVEL = 0.05;
export const LEVEL_DELTA_DMG_CAP = 0.25;

/** Damage multiplier for (attackerLevel − defenderLevel): ±5%/level, capped ±25%. */
export function levelDeltaDamageMultiplier(attackerLevel: number, defenderLevel: number): number {
  const raw = (attackerLevel - defenderLevel) * LEVEL_DELTA_DMG_PER_LEVEL;
  const clamped = Math.max(-LEVEL_DELTA_DMG_CAP, Math.min(LEVEL_DELTA_DMG_CAP, raw));
  return 1 + clamped;
}

/**
 * Hit chance when `attackerLevel` strikes `defenderLevel`. Mobs 4+ levels above
 * the attacker get progressively harder to hit — the classic "don't fight red
 * mobs" signal (GDD §4). Equal/lower defenders are near-certain hits.
 */
export function hitChance(attackerLevel: number, defenderLevel: number): number {
  const over = defenderLevel - attackerLevel;
  if (over < 4) return 0.95;
  return Math.max(0.2, 0.95 - (over - 3) * 0.08);
}

// --- Crit (GDD §4) ---
/** Apply the crit multiplier to a damage/heal amount. */
export function applyCrit(amount: number, isCrit: boolean): number {
  return isCrit ? amount * CRIT_MULTIPLIER : amount;
}

/** Whether a [0,1) roll crits at `critChance`. */
export function isCritRoll(critChance: number, roll: number): boolean {
  return roll < critChance;
}

// --- Threat (GDD §4) ---
export const HEAL_THREAT_FACTOR = 0.5;
export const PULL_THRESHOLD_MELEE = 1.1;
export const PULL_THRESHOLD_RANGED = 1.3;

/** Threat generated by dealing `damage` (tank stance multiplies, default 1). */
export function threatFromDamage(damage: number, tankMultiplier = 1): number {
  return damage * tankMultiplier;
}

/** Threat generated by healing `amount` (0.5/pt, split among engaged enemies by caller). */
export function threatFromHeal(amount: number): number {
  return amount * HEAL_THREAT_FACTOR;
}

// --- Enemy baselines (GDD §4) ---
export enum EnemyRank {
  Normal = 'normal',
  Elite = 'elite',
  Boss = 'boss',
}

// Rank multipliers (GDD §4). Phase-3 SOLO tuning: with no potions and no modelled
// kiting yet, the original ×8 HP / ×2 dmg boss made a 90–180 s attrition fight
// unsurvivable for a no-sustain class (a small HP pool can only absorb ~10–15 s of
// ×2 boss damage). These provisional values keep bosses clearly tougher than elites
// while making every Hollow soloable at-level now; Phase 5's balance pass restores
// longer fights once consumables/defensive cooldowns/kiting are in (GDD §4/§15).
export const RANK_HP_MULT: Record<EnemyRank, number> = {
  [EnemyRank.Normal]: 1,
  [EnemyRank.Elite]: 2.4,
  [EnemyRank.Boss]: 4.5,
};
export const RANK_DMG_MULT: Record<EnemyRank, number> = {
  [EnemyRank.Normal]: 1,
  [EnemyRank.Elite]: 1.3,
  [EnemyRank.Boss]: 1.25,
};

// Group scaling (GDD §4): each nearby player beyond the first adds +60% HP, +15% dmg.
export const GROUP_HP_PER_EXTRA = 0.6;
export const GROUP_DMG_PER_EXTRA = 0.15;

/** Max HP of an enemy of `level` and `rank`, scaled for `nearbyPlayers` (≥1). */
export function enemyMaxHP(level: number, rank = EnemyRank.Normal, nearbyPlayers = 1): number {
  const base = 35 + 22 * level + Math.pow(1.1, level) * 8;
  const extra = Math.max(0, nearbyPlayers - 1);
  return Math.round(base * RANK_HP_MULT[rank] * (1 + GROUP_HP_PER_EXTRA * extra));
}

/** Damage of one enemy swing (per the 2 s baseline), scaled for rank + group. */
export function enemyDamage(level: number, rank = EnemyRank.Normal, nearbyPlayers = 1): number {
  const base = 6 + 4 * level;
  const extra = Math.max(0, nearbyPlayers - 1);
  return Math.round(base * RANK_DMG_MULT[rank] * (1 + GROUP_DMG_PER_EXTRA * extra));
}

/** Enemy swing timer baseline (GDD §4: "damage per 2 s swing"). */
export const ENEMY_SWING_SECONDS = 2;
